version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongoContainer
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root1
      MONGO_INITDB_ROOT_PASSWORD: password1
      MONGO_INITDB_DATABASE: myDatabase
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro